name: Android Plugin Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: android-plugin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Version
        run: gradle --version

      - name: Build
        run: gradle assemble

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: NativeMusicPlayer
          path: android-plugin/build/outputs/aar/*.aar
